### ISSUE TITLE
fdrw: module 'numpy' has no attribute 'float128'

### ISSUE THREAD

**Issue by AlienKevin** [sp-nitech/SPTK#40]
## Issue
When running the pitch_voting example on macOS, I got the following error:

Traceback (most recent call last):
  File "../../../bin/fdrw", line 24, in <module>
    import sptk.draw_utils as utils
  File "/Users/kevin/Dev/personal/canto_syllable_classification/SPTK/src/draw/sptk/draw_utils.py", line 56, in <module>
    "e": np.float128,
  File "/Users/kevin/Dev/personal/canto_syllable_classification/SPTK/tools/venv/lib/python3.8/site-packages/numpy/__init__.py", line 320, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float128'

## Workaround
Changing float128 to float64 worked.

## Environment
SPTK: latest commit on Jul 15, 2023. Commit hash: 9654e5964b59c412a067987456e75f766f2a77d5
My system: macOS Monterey on M1 Max

**Comment by takenori-y** [comment]
Thank you for pointing this out.
I have removed an option which was not working to fix the problem.
